.PHONY: all clean install uninstall

all \
: $(and $(OCAMLC),$(BUILDDIR)/$(LIBNAME).cma) \
  $(and $(OCAMLOPT),$(BUILDDIR)/$(LIBNAME).cmxa)

define COMPILE_MLI
$(or \
	$(and $(OCAMLC), \
		$(OCAMLC) $(strip \
			-c $(OCAMLCFLAGS) -o $@ $(OCAML_INCLUDE_FLAGS) -I $(BUILDDIR) $<)), \
	$(and $(OCAMLOPT), \
		$(OCAMLOPT) $(strip \
			-c $(OCAMLOPTFLAGS) -o $@ $(OCAML_INCLUDE_FLAGS) -I $(BUILDDIR) $<)))
endef

$(filter-out $(MLI:.mli=.cmi),$(PAIRED_MLCMI)): $(BUILDDIR)/%.cmi \
: %.mli | $(BUILDDIR)
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(COMPILE_MLI)

$(filter $(MLI:.mli=.cmi),$(PAIRED_MLCMI)): $(BUILDDIR)/%.cmi \
: $(BUILDDIR)/%.mli | $(BUILDDIR)
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(COMPILE_MLI)

define COMPILE_ML_TO_CMO
$(OCAMLC) $(strip \
	-c $(OCAMLCFLAGS) $1 -o $@ $(OCAML_INCLUDE_FLAGS) -I $(BUILDDIR) $<)
endef

$(filter-out $(MLSRC:.ml=.cmo),$(PAIRED_MLCMI:.cmi=.cmo)): $(BUILDDIR)/%.cmo \
: %.ml $(BUILDDIR)/%.cmi
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(call COMPILE_ML_TO_CMO,)

$(filter $(MLSRC:.ml=.cmo),$(PAIRED_MLCMI:.cmi=.cmo)): $(BUILDDIR)/%.cmo \
: $(BUILDDIR)/%.ml $(BUILDDIR)/%.cmi
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(call COMPILE_ML_TO_CMO,)

$(MLONLY_MLCMI:.cmi=.cmo) $(MLCMOB): $(BUILDDIR)/%.cmo: %.ml | $(BUILDDIR)
	@$(and $(filter-out $(MLONLY_MODULES) $(ML_MODULESB),$*),false)
	$(call COMPILE_ML_TO_CMO,-w -70)

define COMPILE_ML_TO_CMX
$(OCAMLOPT) $(strip \
	-c $(OCAMLOPTFLAGS) $1 -o $@ $(OCAML_INCLUDE_FLAGS) -I $(BUILDDIR) $<)
endef

$(filter-out $(MLSRC:.ml=.cmx),$(PAIRED_MLCMI:.cmi=.cmx)): $(BUILDDIR)/%.cmx \
: %.ml $(BUILDDIR)/%.cmi
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(call COMPILE_ML_TO_CMX,)

$(filter $(MLSRC:.ml=.cmx),$(PAIRED_MLCMI:.cmi=.cmx)): $(BUILDDIR)/%.cmx \
: $(BUILDDIR)/%.ml $(BUILDDIR)/%.cmi
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(call COMPILE_ML_TO_CMX,)

$(MLONLY_MLCMI:.cmi=.cmx): $(BUILDDIR)/%.cmx: %.ml | $(BUILDDIR)
	@$(and $(filter-out $(MLONLY_MODULES),$*),false)
	$(call COMPILE_ML_TO_CMX,-w -70)

$(MLONLY_MLCMI): $(BUILDDIR)/%.cmi \
: $(and $(OCAMLC),$(BUILDDIR)/%.cmo) $(and $(OCAMLOPT),$(BUILDDIR)/%.cmx)
	@$(and $(filter-out $(MLONLY_MODULES),$*),false)

$(MLCMIB): $(BUILDDIR)/%.cmi: $(BUILDDIR)/%.cmo
	@$(and $(filter-out $(ML_MODULESB),$*),false)

define COMPILE_C
$(CC) $(strip \
	-c $(OCAMLC_CFLAGS_ALL) -o $@ -isystem "$(OCAMLLIBDIR)" $(C_INCLUDE_FLAGS) $<)
endef

$(filter-out $(CSRC:.c=.o),$(COBJ)): $(BUILDDIR)/%.o: %.c | $(BUILDDIR)
	$(COMPILE_C)

$(filter $(CSRC:.c=.o),$(COBJ)): $(BUILDDIR)/%.o: $(BUILDDIR)/%.c | $(BUILDDIR)
	$(COMPILE_C)

$(BUILDDIR)/$(LIBNAME).cma: $(MLCMO) $(MLCMOB) $(CDLL)
	$(OCAMLC) -a -o $@ $(MLCMO) $(MLCMOB) $(DLLIB) $(CCLIB)

$(BUILDDIR)/$(LIBNAME).cmxa: $(MLCMX) $(CSLL)
	$(OCAMLOPT) -a -o $@ $(MLCMX) $(SLLIB) $(CCLIB)

$(CDLL): $(COBJ)
	$(strip $(MKDLL_ALL) -o $@ $^ $(LDLIB))

$(CSLL): $(COBJ)
	$(ARCMD) rcs $@ $^

$(BUILDDIR):
	mkdir -p $@

clean:
	-rm $(strip \
		$(filter $(BUILDDIR)/%,$(MLI) $(MLSRC) $(CSRC)) \
		$(MLCMI) \
		$(MLCMIB) $(BUILDDIR)/$(LIBNAME).cma $(CDLL) \
		$(MLCMX) $(BUILDDIR)/$(LIBNAME).cmxa $(BUILDDIR)/$(LIBNAME).a $(CSLL) \
		$(MLCMO) $(MLCMOB) $(MLOBJ) $(COBJ))
	-rmdir $(BUILDDIR)

install: all | $(DEST_INSTALLDIR)$(and $(OCAMLC),$(STUBLIBNAME),/stublibs)
	cd $(DEST_INSTALLDIR) && $(INSTALL_DATA) $(strip \
		$(addprefix $(_BUILDDIR_FROM_INSTALLDIR)/,$(_INSTALLED_FILES)) .)
	$(and $(OCAMLC),$(STUBLIBNAME), \
		cd $(DEST_INSTALLDIR)/stublibs && $(INSTALL_PROGRAM) $(strip \
			$(_BUILDDIR_FROM_INSTALLDIRSTUBLIBS)/$(_CDLL) .))

$(DEST_INSTALLDIR)/stublibs:
	mkdir -p $@

$(DEST_INSTALLDIR):
	mkdir -p $@

uninstall:
	-rm $(strip \
		$(addprefix $(DEST_INSTALLDIR)/,$(_INSTALLED_FILES)) \
		$(addprefix $(DEST_INSTALLDIR)/stublibs/,$(_CDLL)))
