.PHONY: all clean install uninstall

all: \
	$(and $(OCAMLC),$(BUILDDIR)/$(LIBNAME).cma) \
	$(and $(OCAMLOPT),$(BUILDDIR)/$(LIBNAME).cmxa)

$(PAIRED_MLCMI): $(BUILDDIR)/%.cmi: %.mli | $(BUILDDIR)
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(or \
		$(and $(OCAMLC),$(OCAMLC) -c $(OCAMLCFLAGS) -o $@ -I $(BUILDDIR) $<), \
		$(and $(OCAMLOPT),$(OCAMLOPT) -c $(OCAMLOPTFLAGS) -o $@ -I $(BUILDDIR) $<))

$(PAIRED_MLCMI:.cmi=.cmo): $(BUILDDIR)/%.cmo: %.ml $(BUILDDIR)/%.cmi
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(OCAMLC) -c $(OCAMLCFLAGS) -o $@ -I $(BUILDDIR) $<

$(PAIRED_MLCMI:.cmi=.cmx): $(BUILDDIR)/%.cmx: %.ml $(BUILDDIR)/%.cmi
	@$(and $(filter-out $(MLI_MODULES),$*),false)
	$(OCAMLOPT) -c $(OCAMLOPTFLAGS) -o $@ -I $(BUILDDIR) $<

$(MLONLY_MLCMI:.cmi=.cmo) $(MLCMOB): $(BUILDDIR)/%.cmo: %.ml | $(BUILDDIR)
	@$(and $(filter-out $(MLONLY_MODULES) $(ML_MODULESB),$*),false)
	$(OCAMLC) -c $(OCAMLCFLAGS) -w -70 -o $@ -I $(BUILDDIR) $<

$(MLONLY_MLCMI:.cmi=.cmx): $(BUILDDIR)/%.cmx: %.ml | $(BUILDDIR)
	@$(and $(filter-out $(MLONLY_MODULES),$*),false)
	$(OCAMLOPT) -c $(OCAMLOPTFLAGS) -w -70 -o $@ -I $(BUILDDIR) $<

$(MLONLY_MLCMI): $(BUILDDIR)/%.cmi: \
		$(and $(OCAMLC),$(BUILDDIR)/%.cmo) $(and $(OCAMLOPT),$(BUILDDIR)/%.cmx)
	@$(and $(filter-out $(MLONLY_MODULES),$*),false)

$(MLCMIB): $(BUILDDIR)/%.cmi: $(BUILDDIR)/%.cmo
	@$(and $(filter-out $(ML_MODULESB),$*),false)

$(BUILDDIR)/%.o: %.c | $(BUILDDIR)
	$(CC) -c $(OCAMLC_CFLAGS_ALL) -o $@ -isystem "$(OCAMLLIBDIR)" $<

$(BUILDDIR)/$(LIBNAME).cma: $(MLCMO) $(MLCMOB) $(CDLL)
	$(OCAMLC) -a -o $@ $(MLCMO) $(MLCMOB) $(DLLIB) $(CCLIB)

$(BUILDDIR)/$(LIBNAME).cmxa: $(MLCMX) $(CSLL)
	$(OCAMLOPT) -a -o $@ $(MLCMX) $(SLLIB) $(CCLIB)

$(and $(STUBLIBNAME),$(BUILDDIR)/dll$(STUBLIBNAME)$(EXT_DLL)): $(COBJ)
	$(MKDLL_ALL) -o $@ $^ $(LDLIB)

$(and $(STUBLIBNAME),$(BUILDDIR)/lib$(STUBLIBNAME).a): $(COBJ)
	$(ARCMD) rcs $@ $^

$(BUILDDIR):
	mkdir -p $@

clean:
	-rm $(strip \
		$(MLCMI) \
		$(MLCMIB) \
		$(BUILDDIR)/$(LIBNAME).cma \
		$(MLCMX) \
		$(BUILDDIR)/$(LIBNAME).cmxa $(BUILDDIR)/$(LIBNAME).a \
		$(and $(STUBLIBNAME), \
			$(BUILDDIR)/lib$(STUBLIBNAME).a \
			$(BUILDDIR)/dll$(STUBLIBNAME)$(EXT_DLL)) \
		$(MLCMO) $(MLCMOB) $(MLOBJ) $(COBJ))
	-rmdir $(BUILDDIR)

install: all | $(INSTALLDIR)$(and $(OCAMLC),$(STUBLIBNAME),/stublibs)
	cd $(INSTALLDIR) && $(INSTALL_DATA) $(strip \
		$(addprefix $(_BUILDDIR_FROM_INSTALLDIR)/,$(_INSTALLED_FILES)) .)
	$(and $(OCAMLC),$(STUBLIBNAME), \
		cd $(INSTALLDIR)/stublibs && $(INSTALL_PROGRAM) $(strip \
			$(_BUILDDIR_FROM_INSTALLDIRSTUBLIBS)/$(notdir $(CDLL)) .))

$(INSTALLDIR)/stublibs:
	mkdir -p $(INSTALLDIR)/stublibs

$(INSTALLDIR):
	mkdir -p $(INSTALLDIR)

uninstall:
	-rm $(strip \
		$(addprefix $(INSTALLDIR)/,$(_INSTALLED_FILES)) \
		$(addprefix $(INSTALLDIR)/stublibs/,$(notdir $(CDLL))))
